# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cpp.proto',
  package='xsd.cpp',
  serialized_pb='\n\tcpp.proto\x12\x07xsd.cpp\"]\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0cinclude_file\x18\x02 \x03(\t\x12\x11\n\tnamespace\x18\x03 \x02(\t\x12\x1e\n\x06\x63lass_\x18\x04 \x03(\x0b\x32\x0e.xsd.cpp.Class\"\xdd\x01\n\x05\x43lass\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0cparent_class\x18\x02 \x03(\t\x12*\n\x0c\x63onstruction\x18\x03 \x01(\x0b\x32\x14.xsd.cpp.Contruction\x12\x1f\n\x06method\x18\x04 \x03(\x0b\x32\x0f.xsd.cpp.Method\x12 \n\nmember_var\x18\x05 \x03(\x0b\x32\x0c.xsd.cpp.Var\x12\x1c\n\x05\x65num_\x18\x06 \x01(\x0b\x32\r.xsd.cpp.Enum\x12#\n\x0binner_class\x18\x07 \x03(\x0b\x32\x0e.xsd.cpp.Class\"-\n\x0b\x43ontruction\x12\x1e\n\x08\x61rgument\x18\x01 \x03(\x0b\x32\x0c.xsd.cpp.Var\"x\n\x06Method\x12\x13\n\x0breturn_type\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1e\n\x08\x61rgument\x18\x03 \x03(\x0b\x32\x0c.xsd.cpp.Var\x12\r\n\x05\x63onst\x18\x04 \x01(\x08\x12\x0e\n\x06static\x18\x05 \x01(\x08\x12\x0c\n\x04\x62ody\x18\x06 \x02(\t\"@\n\x03Var\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05\x63onst\x18\x03 \x01(\x08\x12\x0e\n\x06static\x18\x04 \x01(\x08\"#\n\x04\x45num\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x03(\t')




_FILE = descriptor.Descriptor(
  name='File',
  full_name='xsd.cpp.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='xsd.cpp.File.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='include_file', full_name='xsd.cpp.File.include_file', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='namespace', full_name='xsd.cpp.File.namespace', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='class_', full_name='xsd.cpp.File.class_', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=115,
)


_CLASS = descriptor.Descriptor(
  name='Class',
  full_name='xsd.cpp.Class',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='xsd.cpp.Class.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent_class', full_name='xsd.cpp.Class.parent_class', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='construction', full_name='xsd.cpp.Class.construction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='method', full_name='xsd.cpp.Class.method', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='member_var', full_name='xsd.cpp.Class.member_var', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enum_', full_name='xsd.cpp.Class.enum_', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inner_class', full_name='xsd.cpp.Class.inner_class', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=339,
)


_CONTRUCTION = descriptor.Descriptor(
  name='Contruction',
  full_name='xsd.cpp.Contruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='argument', full_name='xsd.cpp.Contruction.argument', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=341,
  serialized_end=386,
)


_METHOD = descriptor.Descriptor(
  name='Method',
  full_name='xsd.cpp.Method',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='return_type', full_name='xsd.cpp.Method.return_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='xsd.cpp.Method.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='argument', full_name='xsd.cpp.Method.argument', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='const', full_name='xsd.cpp.Method.const', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='static', full_name='xsd.cpp.Method.static', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='body', full_name='xsd.cpp.Method.body', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=508,
)


_VAR = descriptor.Descriptor(
  name='Var',
  full_name='xsd.cpp.Var',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='xsd.cpp.Var.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='xsd.cpp.Var.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='const', full_name='xsd.cpp.Var.const', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='static', full_name='xsd.cpp.Var.static', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=510,
  serialized_end=574,
)


_ENUM = descriptor.Descriptor(
  name='Enum',
  full_name='xsd.cpp.Enum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='xsd.cpp.Enum.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='xsd.cpp.Enum.value', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=576,
  serialized_end=611,
)

_FILE.fields_by_name['class_'].message_type = _CLASS
_CLASS.fields_by_name['construction'].message_type = _CONTRUCTION
_CLASS.fields_by_name['method'].message_type = _METHOD
_CLASS.fields_by_name['member_var'].message_type = _VAR
_CLASS.fields_by_name['enum_'].message_type = _ENUM
_CLASS.fields_by_name['inner_class'].message_type = _CLASS
_CONTRUCTION.fields_by_name['argument'].message_type = _VAR
_METHOD.fields_by_name['argument'].message_type = _VAR
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Class'] = _CLASS
DESCRIPTOR.message_types_by_name['Contruction'] = _CONTRUCTION
DESCRIPTOR.message_types_by_name['Method'] = _METHOD
DESCRIPTOR.message_types_by_name['Var'] = _VAR
DESCRIPTOR.message_types_by_name['Enum'] = _ENUM

class File(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILE
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.File)

class Class(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLASS
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.Class)

class Contruction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTRUCTION
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.Contruction)

class Method(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METHOD
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.Method)

class Var(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VAR
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.Var)

class Enum(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENUM
  
  # @@protoc_insertion_point(class_scope:xsd.cpp.Enum)

# @@protoc_insertion_point(module_scope)
